---
- name: deploy_to_aws
  hosts: localhost
  connection: local
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Run apt update and apt upgrade
    apt:
      update_cache: yes
      upgrade: yes
  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes
  - name: Install docker
    apt:
      name: docker
      state: present
      update_cache: yes
  - name: Install docker-compose
    apt:
      name: docker-compose
      state: present
      update_cache: yes