---
- name: deploy_to_aws
  hosts: localhost
  connection: local
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Run apt update and apt upgrade
    apt:
      update_cache: yes
      upgrade: yes
  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes
  - name: Install docker
    apt:
      name: docker
      state: present
      update_cache: yes
  - name: Install docker-compose
    get_url:
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'