version: '3'
services:
  web:
    image: wenkey/employeeportal-backend
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employee
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
    container_name: employeeportal
    ports: 
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: employee
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  react:
    image: wenkey/employeeportal-frontend
    container_name: react
    environment:
      - REACT_APP_PUBLIC_IP=http://{{ssm:public_ip}}:8080
    ports:
      - 3000:3000
volumes:
  db-data: