#Docker compose
version: '3'
services:
  web:
    build:
      context: .
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employee
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
    container_name: employeeportal
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: employee
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432