on:
  push:
    branches: "**"
jobs:
  spring_boot_application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to docker hub
        uses: dockerhub/login@v1
        with:
          dockerhub-username: ${{secrets.DOCKER_HUB_USERNAME}}
          dockerhub-password: ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/test:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/test:buildcache,mode=max