on:
  push:
    branches: "**"
jobs:
  spring_boot_application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
      - uses: actions/setup-java@v3
        with:
            version: "17"
      - name: Build
      - uses: actions/maven@v3
        with:
            goals: "clean package"
            options:
                "-DskipTests"
      - name: Upload JAR
          #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
      - uses: actions/upload-artifact@v2
        with:
          #Set artifact name
          name: artifact
            #From this path
          path: target/employeeportal-0.0.1-SNAPSHOT.jar
