name: Terraform Destroy
on:
  workflow_dispatch:
jobs:
  tf-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
      - name: terraform destroy
        uses: dflook/terraform-destroy-workspace@v1
        with:
          path: .
          workspace: ${{ github.head_ref }}
